# For running tests locally, see check_in_container target in Makefile

FROM quay.io/packit/base

ARG SOURCE_BRANCH
RUN  if [[ -z $SOURCE_BRANCH ]]; then \
echo -e "\nMissing SOURCE_BRANCH build argument! Please add \
\"--build-arg SOURCE_BRANCH=<val>\" to the build command to specify it!\n\
This is the branch used when installing other Packit projects (e.g. ogr, packit).\n" && exit 1;\
fi

ENV USER=packit \
    HOME=/home/packit

WORKDIR /src

COPY files/ ./files/

# Install  tests deps
RUN ansible-playbook -vv -c local -i localhost, files/install-deps.yaml && \
    ansible-playbook -vv -c local -i localhost, files/recipe-tests.yaml && \
    dnf clean all

# TODO: Write what to do.
