# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

FROM quay.io/packit/packit-worker

ENV USER=packit \
    HOME=/home/packit

RUN set -ex; \
    mkdir -p ${HOME}/.config && \
    echo "deployment: dev" > ${HOME}/.config/packit-service.yaml

COPY files/recipe-tests.yaml ./files/

# Install tests deps
RUN ansible-playbook -vv -c local -i localhost, files/recipe-tests.yaml && \
    dnf clean all

# Allow remote debugging
RUN pip install --upgrade debugpy

# Naive, but works for now
COPY * ./
