name: Rebuild & push images
on:
  workflow_dispatch:
  push:
    branches:
      - test-on-stage

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: files/Containerfile
            image: hardly

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name and set tag
        shell: bash
        run: |
          branch=${GITHUB_REF#refs/heads/}
          tag=""
          case $branch in
              test-on-stage)
                  tag="stg"
                  ;;
          esac
          echo "::set-output name=branch::${branch}"
          unique_tag="${branch}-${GITHUB_SHA::7}"
          echo "::set-output name=tag::${tag} ${unique_tag}"
        id: branch_tag

      - name: Build Image
        id: build-image
        # https://github.com/marketplace/actions/buildah-build
        uses: redhat-actions/buildah-build@v2
        with:
          dockerfiles: ${{ matrix.dockerfile }}
          image: ${{ matrix.image }}
          tags: ${{ steps.branch_tag.outputs.tag }}
          oci: true
          build-args: |
            SOURCE_BRANCH=${{ steps.branch_tag.outputs.branch }}

      - name: Push To Quay
        # https://github.com/marketplace/actions/push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/packit
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}
